name: Auto Merge Dependencies

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-24-04
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    
    permissions:
      contents: write
      pull-requests: write
      checks: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for checks
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          allowed-conclusions: success,skipped
          verbose: true

      - name: Auto merge
        if: success()
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_RETRIES: 3
          MERGE_RETRY_SLEEP: 30000
          UPDATE_LABELS: automerge
          UPDATE_METHOD: rebase